version: "3"

services:
  job_supervisor:
    image: zimoxiao/job_supervisor:latest
    restart: on-failure
    volumes:
    - ../:/job_supervisor:rw
    command: ["/job_supervisor/docker/docker-entrypoint.sh"]
    privileged: true
    ports:
      - "3030:3030"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      OPENCONNECT_PASSWORD: ${OPENCONNECT_PASSWORD}
      OPENCONNECT_USER: ${OPENCONNECT_USER}
      OPENCONNECT_AUTHGROUP: ${OPENCONNECT_AUTHGROUP}
      OPENCONNECT_URL: ${OPENCONNECT_URL}
      OPENCONNECT_MFA_CODE: ${OPENCONNECT_MFA_CODE}
    networks:
      - supervisornet

volumes:
  mysql_volume:

networks:
  supervisornet:
    external:
      name: custom_network
