version: "2.2"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - var_lib_mysql:/var/lib/mysql
    networks:
      - slurmnet

  slurmdbd:
    image: slurm-docker-cluster:19.05.1
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh","slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql
    networks:
      - slurmnet

  slurmctld:
    image: slurm-docker-cluster:19.05.1
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh","slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    ports:
      - "2222:22"
    depends_on:
      - "slurmdbd"
    networks:
      - slurmnet

  c1:
    image: slurm-docker-cluster:19.05.1
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh","slurmd"]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurmnet

  c2:
    image: slurm-docker-cluster:19.05.1
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh","slurmd"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurmnet

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:

networks:
  slurmnet:
      name: custom_network