name: build-core

on:
  push:
    branches:
      - jupyter_globus_issue

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        npm config set //npm.pkg.github.com/:_authToken $TOKEN
        npm install
        npm run build
      env:
        TOKEN: ${{secrets.GITHUB_TOKEN}}
