name: BUILD CYBERGIS COMPUTE IMAGE

on:
  push:
    branches:
      - master
      - v2
    paths:
      - 'Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: alexandermichels/cybergis-compute-core:latest